apiVersion: v1
kind: Service
metadata:
  name: services-flask-docker
spec:
  type: ClusterIP
  selector:
    app: flask-docker
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx  # <--- Este portero tiene la IP pública
  rules:
  - http:
      paths:
      - path: /calc-app(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: services-flask-docker # DEBE coincidir con el nombre del Servicio arriba
            port:
              number: 80

  
